#Filename: SERVICEINFO.CS
#Version: 20100906
#Expiration: 20110102
#Hash: 258d91dff4f72b4316643f39ce39c7d990e1588b
#Reference: http://extranet.dpd.de/georoute/references_dpd_20100906.txt
#Fields: ServiceCode|ServiceFieldInfo|
#Key: ServiceCode|
102|nebezpe?n? zbo?? / hazardous goods|
103|sobota /saturday|
106|ex works / ex works nebezpe?n? zbo?? / hazardous goods|
109|dob?rka / C.O.D.|
110|dob?rka / C.O.D. / nebezpe?n? zbo?? / hazardous goods|
113|v?m?na / exchange|
121|nebezpe?n? zbo?? / hazardous goods|
125|ex works / ex works / nebezpe?n? zbo?? / hazardous goods|
128|dob?rka / C.O.D.|
129|dob?rka / C.O.D. / nebezpe?n? zbo?? / hazardous goods|
132|v?m?na / exchange|
137|sobota / saturday|
140|dob?rka / C.O.D.|
142|v?m?na / exchange|
150|dob?rka / C.O.D.|
152|v?m?na / exchange|
161|DPD GUARANTEE dob?rka / C.O.D.|
174|DPD GUARANTEE dob?rka / C.O.D.|
191|DPD 10:00 dob?rka / C.O.D.|
197|DPD 10:00 v?mena / exchange|
215|DPD 10:00 dob?rka / C.O.D.|
237|DPD 12:00 dob?rka / C.O.D.|
243|DPD 12:00 v?mena  / exchange|
261|DPD 12:00 dob?rka / C.O.D.|
271|stejn? den / same day|
327|SOUKROMA ADRESA / KONTAKTOVAT PRIJEMCE|
328|SOUKROMA ADRESA / KONTAKTOVAT PRIJEMCE|
329|SOUKROMA ADRESA DOBIRKA / KONTAKTOVAT PRIJEMCE|
330|SOUKROMA ADRESA DOBIRKA / KONTAKTOVAT PRIJEMCE|
333|SOUKROMA ADRESA / KONTAKTOVAT PRIJEMCE|
334|SOUKROMA ADRESA / KONTAKTOVAT PRIJEMCE|
335|SOUKROMA ADRESA DOBIRKA / KONTAKTOVAT PRIJEMCE|
336|SOUKROMA ADRESA DOBIRKA / KONTAKTOVAT PRIJEMCE|
352|DPD 8:30 dob?rka / C.O.D.|
353|DPD 8:30 v?mena / exchange|
357|DPD 8:30 dob?rka / C.O.D.|
358|DPD 8:30 dob?rka / exchange|
