#Filename: SERVICEINFO.CS
#Version: 20130506
#Expiration: 20130901
#Hash: 755fd81761d0474d68f00ff70ce4516fa8fef173
#Reference: http://extranet.dpd.de/georoute/references_dpd_20130506.txt
#Fields: ServiceCode|ServiceFieldInfo|
#Key: ServiceCode|
102|nebezpecne zbozi / hazardous goods|
103|sobota /saturday|
106|ex works nebezpecne zbozi / ex works hazardous goods|
109|dobirka / C.O.D.|
110|dobirka nebezpecne zbozi / C.O.D. hazardous goods|
113|vymena / exchange|
117|Collection-upon-Delivery|
121|nebezpecne zbozi / hazardous goods|
124|ex works|
125|ex works nebezpecne zbozi / ex works hazardous goods|
128|dobirka / C.O.D.|
129|dobirka  nebezpecne zbozi / C.O.D. hazardous goods|
132|vymena / exchange|
137|sobota / saturday|
138|ex works|
140|dobirka / C.O.D.|
142|vymena / exchange|
144|Collection-upon-Delivery|
148|ex works|
150|dobirka / C.O.D.|
152|vymena / exchange|
154|DPD PARCELLetter|
155|DPD 18:00 / DPD GUARANTEE|
158|DPD 18:00 ex works / DPD GUARANTEE ex works|
161|DPD 18:00 dobirka / DPD GUARANTEE C.O.D.|
164|DPD 18:00 vymena / DPD GUARANTEE exchange|
168|DPD 18:00 / DPD GUARANTEE|
171|DPD 18:00 ex works / DPD GUARANTEE ex works|
174|DPD 18:00 dobirka / DPD GUARANTEE C.O.D.|
179|DPD 10:00|
185|DPD 10:00 ex works|
191|DPD 10:00 dobirka / C.O.D.|
197|DPD 10:00 vymena / exchange|
203|DPD 10:00|
209|DPD 10:00 ex works|
215|DPD 10:00 dobirka / C.O.D.|
225|DPD 12:00|
228|DPD 12:00 sobota / Saturday|
231|DPD 12:00 ex works|
234|DPD 12:00 sobota ex works / Saturday ex works|
237|DPD 12:00 dobirka / C.O.D.|
240|DPD 12:00 sobota dobirka / Saturday C.O.D.|
243|DPD 12:00 vymena  / exchange|
249|DPD 12:00|
252|DPD 12:00 sobota / Saturday|
255|DPD 12:00 ex works|
258|DPD 12:00 sobota ex works / Saturday ex works|
261|DPD 12:00 dobirka / C.O.D.|
271|stejny den / same day|
327|PRIVATE ADDRESS / B2C|
328|PRIVATE ADDRESS / B2C|
329|PRIVATE ADDRESS / B2C - C.O.D.|
330|PRIVATE ADDRESS / B2C - C.O.D.|
333|SOUKROMA ADRESA / KONTAKTOVAT PRIJEMCE|
334|SOUKROMA ADRESA / KONTAKTOVAT PRIJEMCE|
335|SOUKROMA ADRESA DOBIRKA / KONTAKTOVAT PRIJEMCE|
336|SOUKROMA ADRESA DOBIRKA / KONTAKTOVAT PRIJEMCE|
352|DPD 8:30 dobirka / C.O.D.|
353|DPD 8:30 vymena / exchange|
357|DPD 8:30 dobirka / C.O.D.|
358|DPD 8:30 vymena / exchange|
839|VECERNI DORUCENI 17:00-20:00|
840|VECERNI DORUCENI 17:00-20:00|
841|VECERNI DORUCENI 17:00-20:00 DOBIRKA|
842|VECERNI DORUCENI 17:00-20:00 DOBIRKA|
